language: python
python:
    - "3.8"
install:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
script:
    - pytest
after_success:
    - coveralls