language: python
python:
    - "3.8"
    - "3.7"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r requirements.dev.txt
script:
    - coverage run -m pytest tests/
after_success:
    - coveralls